version: '3'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile-dev
    networks:
      - network
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    env_file:
      - .env
  db:
    container_name: db
    image: mysql:8
    restart: always
    networks:
      - network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  pubsub:
    container_name: pubsub
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:434.0.0-emulators
    command: "gcloud beta emulators pubsub start --host-port=0.0.0.0:8085"
    restart: always
    networks:
      - network
    ports:
      - "8085:8085"
    expose:
      - "8085"
    env_file:
      - .env

volumes:
  db_data:
    driver: local

networks:
  network:
    driver: bridge
