version: '3'

services:
  app:
    build:
      context: .
      dockerfile: build/dev.Dockerfile
    ports:
      - "8080:8080"
      - "40000:40000" # Delve debugger port
    volumes:
      - .:/app
    networks:
      - app
    environment:
      - NAME=my-app
      - PRODUCTION=false
      - PORT=8080
      #- DATABASE_DSN=root:testtest@tcp(host.docker.internal:3306)/ankorstore # local monolith MySQL

networks:
  app:
