version: '3'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    env_file:
      - .env
