version: '3'

services:
  # -------------------
  # App ---------------
  # -------------------
  search_app:
    container_name: search_app
    build:
      dockerfile: Dockerfile-dev
    networks:
      - search_network
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    env_file:
      - .env
  # -------------------
  # Database ----------
  # -------------------
  search_db:
    container_name: search_db
    image: mysql:8
    restart: always
    networks:
      - search_network
    ports:
      - "${COMPOSE_SEARCH_DB_PORT:-3306}:3306"
    expose:
      - "3306"
    volumes:
      - search_db_data:/var/lib/mysql
    env_file:
      - .env
  # -------------------
  # Redis cache -------
  # -------------------
  search_redis:
    container_name: search_redis
    image: "redis:latest"
    restart: always
    command: --port 6380
    ports:
      - "${COMPOSE_REDIS_PORT:-6380}:6380"
    networks:
      - search_network
  # -------------------
  # Redis commander ---
  # -------------------
  search_redis_commander:
    container_name: search_redis_commander
    image: rediscommander/redis-commander
    networks:
        - search_network
    ports:
      - "${COMPOSE_REDIS_COMMANDER_PORT:-8181}:8081"
    environment:
      - REDIS_HOSTS=local:search_redis:6380
# -------------------
# Misc --------------
# -------------------
volumes:
  search_db_data:
    driver: local
networks:
  search_network:
    driver: bridge
