version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
