version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
      - "40000:40000" # Delve debugger port
    volumes:
      - .:/app
    networks:
      - app
    env_file:
      - .env

networks:
  app:
