app:
  name: "search"
  version: "0.0.1"
http:
  server:
    port: 8080
database:
  driver: mysql
  dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
traces:
  enabled: ${TRACES_ENABLED}
  collector: ${TRACES_COLLECTOR}
config:
    call:
      url: http://localhost:8080/answer
    answer:
      should_fail: false
    datascience-api:
      url: ${DATA_API_URL}
      key: ${DATA_API_KEY}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}