app:
  name: "go-skel"
  version: "0.0.1"
http:
  server:
    port: 8080
database:
  driver: mysql
  dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
config:
    foo: bar-default