app:
  name: ${APP_NAME}
  debug: false
  version: "0.1.0"
modules:
  auth:
    enabled: true
    blocking: true
  logger:
    level: info
  tracer:
    enabled: true
    exporter: noop
  http:
    server:
      port: 8080
    tracer:
      enabled: true
  grpc:
    server:
      port: 50051
      reflection: true
    tracer:
      enabled: true
  gorm:
    dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
    driver: mysql
    logger:
      level: info
      with_values: false
    tracer:
      enabled: true
      with_values: false
  pubsub:
    topics:
      test: test-topic
    subscriptions:
      test: test-topic-sub
config:
    ping:
      url: ${PONG_URL}
    pong:
      should_fail: false
    test:
      value: common
    datascience-api:
      url: ${DATA_API_URL}
      key: ${DATA_API_KEY}
    elastic:
      host: ${ELASTIC_HOST}
      port: ${ELASTIC_PORT}
      user: ${ELASTIC_USER}
      password: ${ELASTIC_PASSWORD}
      prefix: ${ELASTIC_PREFIX}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    recommendation:
      ttl: ${REDIS_RECOMMENDATION_TTL}