app:
  name: "go-skel"
  version: "0.0.2"
http:
  server:
    port: 8080
database:
  driver: mysql
  dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
traces:
  enabled: ${TRACES_ENABLED}
  collector: ${TRACES_COLLECTOR}
pubsub:
  topics:
    test: test-topic
  subscriptions:
    test: test-topic-sub
config:
    ping:
      url: http://localhost:8080/http/pong
    pong:
      should_fail: false