app:
  name: ${APP_NAME}
  version: "0.0.2"
http:
  server:
    port: 8080
  tracer:
    enabled: ${TRACER_ENABLED}
grpc:
  server:
    port: 50051
    reflection: true
  tracer:
    enabled: ${TRACER_ENABLED}
gorm:
  dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
  driver: mysql
  logger:
    level: debug
    with_values: ${APP_DEBUG}
  tracer:
    enabled: ${TRACER_ENABLED}
    with_values: ${APP_DEBUG}
tracer:
  enabled: ${TRACER_ENABLED}
  exporter: ${TRACER_EXPORTER}
  collector: ${TRACER_COLLECTOR}
pubsub:
  topics:
    test: test-topic
  subscriptions:
    test: test-topic-sub
config:
    ping:
      url: ${PONG_URL}
    pong:
      should_fail: false