modules:
  auth:
    blocking: false
  logger:
    level: debug
  tracer:
    exporter: memory
  gorm:
    dsn: file::memory:?cache=shared
    driver: sqlite
  http:
    tracer:
      enabled: true
config:
  test:
    value: testtest