app:
  debug: false
modules:
  logger:
    level: info
  tracer:
    exporter: otlp-grpc
    collector: ${TRACER_COLLECTOR}
  grpc:
    server:
      reflection: false
  gorm:
    logger:
      level: error
      with_values: false
    tracer:
      with_values: false
